# Generated by Django 5.1.6 on 2025-04-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificios',
            fields=[
                ('numero', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('facultad', models.CharField(max_length=255)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('ano', models.CharField(max_length=255)),
                ('carrera', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('full_name', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=255)),
                ('facultad', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
                ('province', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
