# Generated by Django 5.0.6 on 2024-06-25 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vicedecana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificios',
            fields=[
                ('numero', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('facultad', models.CharField(max_length=255)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('ano', models.CharField(max_length=255)),
                ('carrera', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
            },
        ),
        migrations.CreateModel(
            name='Apartamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='Vicedecana.edificios')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('full_name', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=255)),
                ('facultad', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
                ('province', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('apartamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vicedecana.apartamentos')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
