# Generated by Django 5.1.6 on 2025-04-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vicedecana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificios',
            name='apartamento',
            field=models.CharField(default=101, max_length=10),
            preserve_default=False,
        ),
    ]
