# Generated by Django 5.0.6 on 2024-06-25 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vicedecana', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='apartamento',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vicedecana.apartamentos'),
        ),
    ]
