# Generated by Django 5.1.6 on 2025-04-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vicedecana', '0002_edificios_apartamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificios',
            name='apartamento',
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='Vicedecana.edificios')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
            },
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='apartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vicedecana.apartamento'),
        ),
    ]
