# Generated by Django 5.1.6 on 2025-04-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vicedecana', '0003_remove_edificios_apartamento_apartamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='limite_estudiantes',
            field=models.IntegerField(default=12),
        ),
    ]
