# Generated by Django 5.0.6 on 2024-06-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vicedecana', '0004_alter_estudiantes_apartamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes',
            old_name='province',
            new_name='provinc',
        ),
    ]
