# Generated by Django 5.1.6 on 2025-04-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vicedecana', '0004_apartamento_limite_estudiantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartamento',
            name='limite_estudiantes',
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vicedecana.edificios'),
        ),
    ]
