# Generated by Django 5.1.6 on 2025-04-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vicedecana', '0005_remove_apartamento_limite_estudiantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='edificio',
        ),
    ]
