# Generated by Django 5.0.6 on 2024-06-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vicedecana', '0005_rename_province_estudiantes_provinc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes',
            old_name='provinc',
            new_name='province',
        ),
    ]
