# Generated by Django 5.0.6 on 2025-04-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vicedecana', '0006_rename_provinc_estudiantes_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='apartamento',
        ),
        migrations.DeleteModel(
            name='Apartamentos',
        ),
    ]
